
version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins_config:/var/jenkins_home/casc_configs
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/casc.yaml

  worker:
    image: jenkins/inbound-agent:latest
    environment:
      JENKINS_URL: "http://jenkins:8080"
      JENKINS_AGENT_NAME: "worker-1"
      JENKINS_SECRET: "your_agent_secret_here"
    depends_on:
      - jenkins

volumes:
  jenkins_home:
